server:
  port: 18082
# 需要使用 redis 的话，放开这里
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  #spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_oauth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: admin