server:
  port: 18092
# 需要使用 redis 的话，放开这里
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  #spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_oauth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: admin
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jafe.springboot2.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
